core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path

from .views import (
    ReportListView, ReportDetailView, UploadTemplateView,
    create_report_view, render_pdf_view, csv_upload_view
)


app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('file/', UploadTemplateView.as_view(), name='from-file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf', render_pdf_view, name='pdf'),
]

reports/models.py
from django.db import models
from django.urls import reverse

from profiles.models import Profile


class Report(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-created',)

reports/forms.py
from django import forms

from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks',)

reports/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.views.generic import ListView, DetailView, TemplateView
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from django.utils.dateparse import parse_date
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Report
from .forms import ReportForm
from .utils import get_report_image

from profiles.models import Profile
from customers.models import Customer
from products.models import Product
from sales.models import Sale, Position, CSV

from xhtml2pdf import pisa

import csv


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'


@login_required
def csv_upload_view(request):
    print('file is being sent')
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)

        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__()
                for row in reader:
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    date = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None
                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(
                            name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(
                            product=product_obj, quantity=quantity, created=date)
                        sales_obj, _ = Sale.objects.get_or_create(
                            transaction_id=transaction_id, customer=customer_obj,
                            salesman=salesman_obj, created=date)
                        sales_obj.positions.add(position_obj)
                        sales_obj.save()
                return JsonResponse({'ex': False})
        else:
            return JsonResponse({'ex': True})
    return HttpResponse('Hello')


@login_required
def create_report_view(request):
    form = ReportForm(request.POST or None)
    if request.is_ajax():
        # name = request.POST.get('name')
        # remarks = request.POST.get('remarks')
        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)

        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.image = img
            form_instance.author = author
            form_instance.save()
        # Report.objects.create(
            # name=name, remarks=remarks, image=img, author=author,)
        return JsonResponse({'msg': 'send'})
    return JsonResponse({'error': 'something went wrong'})


@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    # obj = Report.objects.get(pk=pk)
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # use this option for direct download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # use this option for viewing as pdf
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}

{% if object.image %}
<img src="{{ object.image.url }}" class="img-fluid" alt="{{ object.name }}">
{% endif %}
<br>
<h3>Remarks</h3>
<p>{{ object.remarks }}</p>
<hr>
<p>author: <b>{{ object.author.user.username }}</b></p>
<p>created: <b>{{ object.created }}</b></p>

{% endblock %}

reports/templates/reports/from_file.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock %}

{% block title %}Upload sales file{% endblock %}

{% block content %}

<h2>Upload sales documents</h2>
<hr>
<div id="alert-box"></div>
<form id="my-dropzone" class="dropzone dz">
    {% csrf_token %}
    <div class="fallback">
        <input name="file" type="file" multiple />
    </div>
</form>

{% endblock %}

reports/templates/reports/main.html
{% extends 'base.html' %}

{% block title %}Reports{% endblock %}

{% block content %}
<h2>Reports</h2>
<hr>
{% for obj in object_list %}
<div class="card mb-3">
    {% if obj.image %}
    <img src="{{ obj.image.url }}" class="card-img-top" alt="{{ obj.name }}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ obj.name }}</h5>
        <p class="card-text">
            {{ obj.remarks | truncatewords:64 }}
        </p>
        <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">details</a>
        <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger">generate pdf</a>
    </div>
</div>
<br>
{% endfor %}

{% endblock %}

reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF {{ obj.name }}</title>
    <style>
        .image {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <h1>{{ obj.name }}</h1>
    <hr>
    <img src="{{ obj.image.path }}" class="image">
    <br>
    <h3>Remarks</h3>
    <p>{{ obj.remarks }}</p>
    <hr>
    <p>author: <b>{{ obj.author.user.username }}</b></p>
    <p>created: <b>{{ obj.created }}</b></p>
</body>
</html>