core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path

from .views import my_profile_view


app_name = 'profiles'

urlpatterns = [
    path('', my_profile_view, name='profile'),
]

reports/urls.py
from django.urls import path

from .views import (
    ReportListView, ReportDetailView, UploadTemplateView,
    create_report_view, render_pdf_view, csv_upload_view
)


app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('file/', UploadTemplateView.as_view(), name='from-file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf', render_pdf_view, name='pdf'),
]

sales/urls.py
from django.urls import path

from .views import (
    SalesListView, SalesDetailView,
    home_view,
)


app_name = 'sales'
urlpatterns = [
    path('', home_view, name='home'),
    path('list/', SalesListView.as_view(), name='list'),
    path('sales/<pk>/', SalesDetailView.as_view(), name='detail'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone css & js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom css & js -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock %}

    <title>Django Sales | {% block title %}{% endblock %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>

</html>

templates/navbar.html
{% url 'sales:home' as path_to_home %}
{% url 'sales:list' as path_to_sales %}
{% url 'reports:main' as path_to_main %}
{% url 'reports:from-file' as path_to_file %}
{% url 'profiles:profile' as path_to_profile %}

{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path_to_home }}"><img src="{% static 'logo.png' %}" class="logo-sm"></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href="{{ path_to_home }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_sales %}active{% endif %}" href="{{ path_to_sales }}">Sales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_file %}active{% endif %}" href="{{ path_to_file }}">Add from file</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_main %}active{% endif %}" href="{{ path_to_main }}">Reports</a>
                </li>
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
            <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <img src="{{ request.user.profile.avatar.url }}" class="avatar-sm">&nbsp;{{request.user}}
            </div>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item {% if request.path == path_to_profile %}active{% endif %}" href="{{ path_to_profile }}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>